### ISSUE TITLE
Improve speed in workflow build-related operations

### ISSUE THREAD

**Issue by matuella** [olmps/memo#94]
Not sure if this is a limitation of the images that we are using or what, but both release and PR workflows are slow. ​

What could we do to improve these build times (possibly [caching](https://github.com/actions/cache)?

**Comment by matuella** [comment]
@ggirotto what do you think about this?

**Comment by ggirotto** [comment]
I have a strong hypothesys about speeding up the `release` workflow. Today we build the iOS app twice: first by using `flutter build` and second by using `build_ios_app` fastlane action. I'm almost sure that we could just remove the `build_ios_app` fastlane action and keep just `flutter build`. I've notes on my side to test it, but I haven't tested yet.

In the `pull_request` workflow, we could definitely cache flutter SDK. I've tried for a few hours, but without success I gave up because this github actions task were taking to long, but now I think we could go back and improve this caching stuff
Cache reference: https://github.com/subosito/flutter-action/issues/16

**Comment by matuella** [comment]
I think #98 resulted in a decent performance improvement (I guess it was around ~33% of less time spent passing the workflow).

@ggirotto Are there other improvements that comes to your mind in both `pull_request` and `release` workflows that we can keep track, or do you think the time vs benefits are not worth to further improve the total time spent?

**Comment by ggirotto** [comment]
I had another hypothesis about caching the Flutter setup, but since the time taken to setup Flutter env is of only ~50 seconds I don't think it will bring great benefits to the overall build time.

**Comment by matuella** [comment]
Closing as we've reached a decent improvement with #98, although we can still look forward to more improvements if they appear plausible
